# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/jking/.podman/logstash/logstash.conf:z
    io.kubernetes.cri-o.SandboxID/elasticsearch: ef232555f844b4ddf305aa9d3a7f098df6f1ea122f0a09c66d2690b22b510430
    io.kubernetes.cri-o.SandboxID/kibana: ef232555f844b4ddf305aa9d3a7f098df6f1ea122f0a09c66d2690b22b510430
    io.kubernetes.cri-o.SandboxID/logstash: ef232555f844b4ddf305aa9d3a7f098df6f1ea122f0a09c66d2690b22b510430
  creationTimestamp: "2025-02-11T21:21:00Z"
  labels:
    app: elk
  name: elk
spec:
  containers:
  - args:
    - eswrapper
    env:
    - name: ELASTIC_PASSWORD
      value: elastic
    image: localhost/elastic:latest
    name: elasticsearch
    ports:
    - containerPort: 5044
      hostPort: 5044
    - containerPort: 5601
      hostPort: 5601
    - containerPort: 9200
      hostPort: 9200
    securityContext: {}
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: es-data-pvc
  - args:
    - /usr/local/bin/kibana-docker
    env:
    - name: ELASTICSEARCH_PASSWORD
      value: kibana
    - name: ELASTICSEARCH_USERNAME
      value: kibana_user
    image: docker.elastic.co/kibana/kibana:8.15.2
    name: kibana
    securityContext:
      runAsNonRoot: true
  - image: docker.elastic.co/logstash/logstash:8.15.2
    name: logstash
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /usr/share/logstash/pipeline/logstash.conf
      name: home-jking-.podman-logstash-logstash.conf-host-0
    - mountPath: /usr/share/logstash/config/logstash.yml
      name: home-jking-.podman-logstash-logstash.yml-host-1
  volumes:
  - name: es-data-pvc
    persistentVolumeClaim:
      claimName: es-data
  - hostPath:
      path: /home/jking/.podman/logstash/logstash.conf
      type: File
    name: home-jking-.podman-logstash-logstash.conf-host-0
  - hostPath:
      path: /home/jking/.podman/logstash/logstash.yml
      type: File
    name: home-jking-.podman-logstash-logstash.yml-host-1
