services:
  # No SQL database
  elasticsearch:
    build: ./elastic
    container_name: elasticsearch
    env_file: ./elastic/.env
    mem_limit: 2g
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "--user", "elastic:elastic", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Web application that works with elasticsearch. Allows user to visualize data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    links:
      - "elasticsearch"
    env_file: ./elastic/.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD", "curl", "--user", "elastic:elastic", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Logging service. Works with both IMX and IMX Server. Stores data in elasticsearh.
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - '9880:9880'
      - "24224:24224"
      - "24224:24224/udp"

volumes:
  es-data:
    driver: local